FROM ruby:3.3.0 AS builder

WORKDIR /app

RUN apt-get update && \
    apt-get install -y nodejs

COPY Gemfile Gemfile.lock /app/
RUN gem install bundler && bundle install

COPY . /app

RUN RAILS_ENV=production bundle exec rake assets:precompile

FROM ruby:3.3.0

WORKDIR /app

COPY --from=builder /app /app

RUN apt-get update && \
    apt-get install -y nodejs

CMD ["rails", "server", "-b", "0.0.0.0", "-e", "production"]
