version: '3'
services:
  mysql:
    image: mysql:8.2
    ports:
      - "13306:3306"
    volumes:
      - ./src/db/mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
  rails:
    build:
      context: .
      dockerfile: Dockerfile
    command: bundle exec rails s -p 8888 -b '0.0.0.0'
    volumes:
      - './src:/app'
    ports:
      - '8888:8888'
    depends_on:
      - mysql
    tty: true
