version: '3'
services:
  mysql:
    image: mysql:8.2
    ports:
      - "13306:3306"
    volumes:
      - db-volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
  rails:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bundle exec rails s -p 8888 -b '0.0.0.0'
    volumes:
      - ./src:/app
      - app_bundle:/usr/local/bundle
    ports:
      - '8888:8888'
    depends_on:
      - mysql
    tty: true
volumes:
  db-volume:
  app_bundle:
