openapi: '3.0.0'
info:
  title: todo_app_api
  description: This simple todo app is written in Ruby on Rails
  version: 1.0.0
tags:
  - name: Register
  - name: Login
  - name: Users
  - name: Todos
paths:
  /register:
    post:
      tags:
        - Register
      summary: Register a user.
      requestBody:
        description: Infomation to register a user.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterUser'
            example:
              name: 'name'
              email: 'abc@example.com'
              password: 'password'
      responses:
        '201':
          description: Registration succeed.
        '422':
          description: Unprocessable entity.
  /login:
    post:
      tags:
        - Login
      summary: Login user.
      requestBody:
        description: Information to login user.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginUser'
            example:
              email: 'abc@example.com'
              password: 'password'
      responses:
        '200':
          description: Login succeed.
        '401':
          description: Unauthorized.
  /users/{user_id}/todos:
    # TODO: add bearer auth
    get:
      tags:
        - Todos
      summary: List of user's todos.
      parameters:
        - name: user_id
          in: path
          description: User's id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Array of todos.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/responses/Todo'
    post:
      tags:
        - Todos
      summary: Create a new todo
      parameters:
        - name: user_id
          in: path
          description: User's id
          required: true
          schema:
            type: integer
      requestBody:
        description: Information to create a new todo
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Todo'
              example:
                - id: 1
                  title: 'Title1'
                  status: 'Status1'
                  target_completion_date: 'YYYY-MM-DD'
      responses:
        '201':
          description: Create todo succeed.
  /users/{user_id}/todos/{id}:
    get:
      tags:
        - Todos
      summary: User's todo details
      parameters:
        - name: user_id
          in: path
          description: User's id
          required: true
          schema:
            type: integer
        - name: id
          in: path
          description: Todo's id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Object of todo.
          content:
            application/json:
              schema:
                $ref: '#/components/responses/Todo'
    put:
      tags:
        - Todos
      summary: Update a todo
      parameters:
        - name: user_id
          in: path
          description: User's id
          required: true
          schema:
            type: integer
        - name: id
          in: path
          description: Todo's id
          required: true
          schema:
            type: integer
      requestBody:
        description: Information to create a new todo. 空が送られたら更新しない
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Todo'
      responses:
        '201':
          description: Update todo succeed.
    delete:
      tags:
        - Todos
      summary: Delete a todo
      parameters:
        - name: user_id
          in: path
          description: User's id
          required: true
          schema:
            type: integer
        - name: id
          in: path
          description: Todo's id
          required: true
          schema:
            type: integer
      responses:
        '201':
          description: Delete todo succeed.
  /users/{user_id}:
    put:
      tags:
        - Users
      summary: Rename user.
      parameters:
        - name: user_id
          in: path
          description: User's id
          required: true
          schema:
            type: integer
      requestBody:
        description: Able to request only name for this path
        content:
          application/json:
            schema:
              type: object
              required:
                - name
              properties:
                name:
                  type: string
      responses:
        '200':
          description: Rename succeed.
  /users/{user_id}/password_update:
    put:
      tags:
        - Users
      summary: Change password
      parameters:
        - name: user_id
          in: path
          description: User's id
          required: true
          schema:
            type: integer
      requestBody:
        description: Information to change password
        content:
          application/json:
            schema:
              type: object
              required:
                - current_password
                - password
                - password_confirm
              properties:
                current_password:
                  type: string
                password:
                  type: string
                password_confirm:
                  type: string
      responses:
        '201':
          description: Change password succeed.
        '400':
          description: Password confirmation is diffrent from password
  /users/{user_id}/password/forgot:
    post:
      tags:
        - Users
      summary: Reset password if forgot
      parameters:
        - name: user_id
          in: path
          description: User's id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Sent password reset mail
  /users/{user_id}/password/reset:
    post:
      tags:
        - Users
      summary: Reset password if forgot
      parameters:
        - name: user_id
          in: path
          description: User's id
          required: true
          schema:
            type: integer
        - name: token
          in: query
          description: reset token
          required: true
          schema:
            type: string
      requestBody:
        description: New password
        content:
          application/json:
            schema:
              type: object
              required:
                - password
              properties:
                password:
                  type: string
      responses:
        '200':
          description: Sent password reset mail

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    RegisterUser:
      type: object
      required:
        - email
        - name
        - password
      properties:
        name:
          type: string
        email:
          type: string
        password:
          type: string
    LoginUser:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
        password:
          type: string
    Todo:
      type: object
      required:
        - title
        - content
        - status
        - target_completion_date
      properties:
        title:
          type: string
        content:
          type: string
        status:
          type: string
        target_completion_date:
          type: string
  responses:
    Todo:
      type: object
      description: Response of create todos.
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
        content:
          type: string
        status:
          type: string
        target_completion_date:
          type: string
        user_id:
          type: integer
          format: int64
        created_at:
          type: string
        update_at:
          type: string
